apiVersion: v1
kind: Service
metadata:
  labels:
    app: model
  name: model
spec:
  type: NodePort
  ports:
  - name: "28101"
    port: 28101
    targetPort: 28101
  - name: "debug"
    port: 5071
    targetPort: 5071
  selector:
    app: model
