kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: uiproxy-edit
 namespace: default
subjects:
- kind: ServiceAccount
  name: uiproxy
  namespace: default
roleRef:
 kind: ClusterRole
 name: edit
 apiGroup: rbac.authorization.k8s.io