apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ui-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ui
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 67