apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app: ui
  name: ui
spec:
  type: NodePort
  ports:
  - name: "33333"
    port: 33333
    targetPort: 33333
  selector:
    app: ui
status:
  loadBalancer: {}
