apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: workspace-uploads
  name: workspace-uploads
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
