language: java
install: true

jdk: 
  - openjdk11
  - openjdk14

script:
  - ./gradlew build
  
cache:
  directories:
  - artifacts
  - $HOME/.m2
  - .gradle
  - ui-client/.gradle/nodejs
  - ui-client/.gradle/npm
