language: java
install: true

jdk: 
  - openjdk11

jobs:
  include:
    - stage: build
      script: ./gradlew build
      if: tag IS blank
    - stage: deploy
      script: ./gradlew build bintrayUpload
      if: tag IS present
  
cache:
  directories:
  - artifacts
  - $HOME/.m2
  - .gradle
  - ui-client/.gradle/nodejs
  - ui-client/.gradle/npm
