
nameOverride: ""
fullnameOverride: ""

imageTags:
  db: ""
  instancesManager: ""
  model: "1.3.2"
  oauth: ""
  proxy: ""
  wsClient: ""
  wsManager: ""

modelStorageSize: 3000Mi

developmentMode: false

keycloak:
  adminPassword: "modelix"
  realm: "modelix"
  clientId: "modelix"
  clientSecret: ""
  loglevel: "warn"
  debug: false

workspaces:
  enabled: true
  uploadsStorageSize: 5000Mi

ingress:
  installController: true
  hostname: "localhost"
  port: ""
  certSecret: ""
  tls:
    crt: ""
    key: ""

db:
  useGCloud: false
  user: "modelix"
  password: "modelix"
  db: "modelix"
  storage: 3000Mi

dockerProxy:
  prefix: ""
  secret: ""
  secret64: ""

serviceAccount: ""