apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ include "modelix.fullname" . }}-ingress"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
spec:
  ingressClassName: nginx
  {{ if or .Values.ingress.certSecret .Values.ingress.tls.crt }}
  tls:
  - hosts:
    - "{{ .Values.ingress.hostname }}"
    {{ if .Values.ingress.tls.crt }}
    secretName: "{{ include "modelix.fullname" . }}-tls-secret"
    {{ else }}
    secretName: "{{ .Values.ingress.certSecret }}"
    {{ end }}
  {{ end }}
  rules:
    - host: "{{ .Values.ingress.hostname }}"
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: "{{ include "modelix.fullname" . }}-keycloak"
                port:
                  number: 8080
            path: /(resources|admin|js|realms)/.*
          - pathType: Prefix
            backend:
              service:
                name: "{{ include "modelix.fullname" . }}-oauth"
                port:
                  number: 4180
            path: /

