apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ include "modelix.fullname" . }}-ingress"
spec:
  ingressClassName: nginx
  rules:
    - host: "{{ .Values.external.hostname }}"
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: "{{ include "modelix.fullname" . }}-oauth"
                port:
                  number: 4180
            path: /
    - host: "{{ .Values.external.keycloak.hostname }}"
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: "{{ include "modelix.fullname" . }}-keycloak"
                port:
                  number: 8080
            path: /

