apiVersion: v1
kind: Service
metadata:
  name: "{{ include "modelix.fullname" . }}-keycloak"
  labels:
    component: keycloak
    {{- include "modelix.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    component: keycloak
    {{- include "modelix.selectorLabels" . | nindent 4 }}
  type: NodePort
