apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "modelix.fullname" . }}-keycloak"
  labels:
    component: keycloak
    {{- include "modelix.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: keycloak
      {{- include "modelix.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        component: keycloak
        {{- include "modelix.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:18.0.1
        args: ["start-dev"]
        env:
        - name: KC_LOG_LEVEL
          value: "warn"
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: "{{ include "modelix.fullname" . }}-config"
              key: keycloak-admin-password
        - name: KC_PROXY
          value: "none"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: KC_DB
          value: "postgres"
        - name: KC_DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: "{{ include "modelix.fullname" . }}-config"
              key: db-user
        - name: KC_DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: "{{ include "modelix.fullname" . }}-config"
              key: db-password
        - name: KC_DB_URL
          value: "jdbc:postgresql://db:5432/"
        - name: KC_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: "{{ include "modelix.fullname" . }}-config"
              key: external-hostname
        - name: KC_HOSTNAME_PORT
          valueFrom:
            configMapKeyRef:
              name: "{{ include "modelix.fullname" . }}-config"
              key: external-port
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080
