kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: "{{ include "modelix.fullname" . }}-sa-edit"
 namespace: default
subjects:
- kind: ServiceAccount
  name: "{{ include "modelix.fullname" . }}-sa"
  namespace: default
roleRef:
 kind: ClusterRole
 name: edit
 apiGroup: rbac.authorization.k8s.io