{{ if .Values.ingress.tls.crt }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "modelix.fullname" . }}-tls-secret"
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.tls.crt }}
  tls.key: {{ .Values.ingress.tls.key }}
{{ end }}