apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: workspace-manager
    {{- include "modelix.labels" . | nindent 4 }}
  name: "{{ include "modelix.fullname" . }}-workspace-manager"
spec:
  revisionHistoryLimit: 5
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      component: workspace-manager
      {{- include "modelix.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        component: workspace-manager
        {{- include "modelix.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
          - name: model_server_url
            value: http://model:28101/
          - name: CLIENT_SECRET
            value: "{{ .Values.keycloak.clientSecret }}"
        image: "modelix/modelix-workspace-manager:{{ .Values.imageTags.wsManager | default .Chart.AppVersion }}"
        imagePullPolicy: IfNotPresent
        name: workspace-manager
        ports:
        - containerPort: 28104
        - containerPort: 5071
          name: "jvm-debug"
        resources: 
          requests:
            memory: "3Gi"
            cpu: "0.1"
          limits:
            memory: "3Gi"
            cpu: "1.0"
        readinessProbe:
          httpGet:
            path: /health
            port: 28104
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 28104
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 10
        volumeMounts:
          - mountPath: "/workspace-manager/modelix-workspaces/uploads"
            name: workspace-uploads
          - name: workspacesecret
            mountPath: /secrets/workspacesecret
            readOnly: true
      restartPolicy: Always
      volumes:
        - name: workspace-uploads
          persistentVolumeClaim:
            claimName: workspace-uploads
        - name: workspacesecret
          secret:
            secretName: workspacesecret
