name: Publish

on:
  push:
    tags:
      - '**'

jobs:
  newRelease:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Use tag as version
      run: echo "${GITHUB_REF#refs/*/}" > modelix.version
    - name: Package Helm Chart
      run: ./helm/publish.sh
    - name: Upload Helm Chart
      uses: actions/upload-artifact@v3
      with:
        name: helm-chart
        path: helm/repo/
    - name: Build and Publish
      env:
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_HUB_KEY: ${{ secrets.DOCKER_HUB_KEY }}
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./gradlew assemble publish && ./docker-ci.sh
